[package]
name = "crudapi"
version = "0.1.0"
edition = "2021"
[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json"]}
reqwest = { version = "0.11.13", features = ["json"]}
lru_time_cache =  "0.11.11"